//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderPaymentSystem.Domain.Resources; 
using System;


/// <summary>
///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
/// </summary>
// Этот класс создан автоматически классом StronglyTypedResourceBuilder
// с помощью такого средства, как ResGen или Visual Studio.
// Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
// с параметром /str или перестройте свой проект VS.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class ErrorMessage {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal ErrorMessage() {
    }
    
    /// <summary>
    ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderPaymentSystem.Domain.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
    ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Элемент корзины с Id {0} не найден.
    /// </summary>
    public static string BasketItemNotFound {
        get {
            return ResourceManager.GetString("BasketItemNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Внутренняя ошибка сервера.
    /// </summary>
    public static string InternalServerError {
        get {
            return ResourceManager.GetString("InternalServerError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Не валидный запрос клиента.
    /// </summary>
    public static string InvalidClientRequest {
        get {
            return ResourceManager.GetString("InvalidClientRequest", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Не валидный токен.
    /// </summary>
    public static string InvalidToken {
        get {
            return ResourceManager.GetString("InvalidToken", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Изменений не найдено.
    /// </summary>
    public static string NoChangesFound {
        get {
            return ResourceManager.GetString("NoChangesFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Не хватает средств для оплаты.
    /// </summary>
    public static string NotEnoughPayFunds {
        get {
            return ResourceManager.GetString("NotEnoughPayFunds", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Элемент заказа не найден.
    /// </summary>
    public static string OrderItemNotFound {
        get {
            return ResourceManager.GetString("OrderItemNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Заказ не найден.
    /// </summary>
    public static string OrderNotFound {
        get {
            return ResourceManager.GetString("OrderNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Заказы не найдены.
    /// </summary>
    public static string OrdersNotFound {
        get {
            return ResourceManager.GetString("OrdersNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Неверный пароль.
    /// </summary>
    public static string PasswordIsWrong {
        get {
            return ResourceManager.GetString("PasswordIsWrong", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Пароли не равны.
    /// </summary>
    public static string PasswordNotEqualsPasswordConfirm {
        get {
            return ResourceManager.GetString("PasswordNotEqualsPasswordConfirm", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Платёж уже существует для заказа с Id {0}.
    /// </summary>
    public static string PaymentAlreadyExistsForOrder {
        get {
            return ResourceManager.GetString("PaymentAlreadyExistsForOrder", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Платёж не найден.
    /// </summary>
    public static string PaymentNotFound {
        get {
            return ResourceManager.GetString("PaymentNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Платёж не связан с заказом.
    /// </summary>
    public static string PaymentOrderNotAssociated {
        get {
            return ResourceManager.GetString("PaymentOrderNotAssociated", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Платежи не найдены.
    /// </summary>
    public static string PaymentsNotFound {
        get {
            return ResourceManager.GetString("PaymentsNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Товар уже существует.
    /// </summary>
    public static string ProductAlreadyExist {
        get {
            return ResourceManager.GetString("ProductAlreadyExist", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Товар с Id {0} не найден.
    /// </summary>
    public static string ProductNotFound {
        get {
            return ResourceManager.GetString("ProductNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Товары не найдены.
    /// </summary>
    public static string ProductsNotFound {
        get {
            return ResourceManager.GetString("ProductsNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Количества товара с Id {0} не хватает на складе.
    /// </summary>
    public static string ProductStockQuantityNotAvailable {
        get {
            return ResourceManager.GetString("ProductStockQuantityNotAvailable", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Время жизни токена истекло.
    /// </summary>
    public static string RefreshTokenExpired {
        get {
            return ResourceManager.GetString("RefreshTokenExpired", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Роль с таким названием уже существует.
    /// </summary>
    public static string RoleAlreadyExist {
        get {
            return ResourceManager.GetString("RoleAlreadyExist", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Роль не найдена.
    /// </summary>
    public static string RoleNotFound {
        get {
            return ResourceManager.GetString("RoleNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Роли не найдены.
    /// </summary>
    public static string RolesNotFound {
        get {
            return ResourceManager.GetString("RolesNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Пользователь уже существует.
    /// </summary>
    public static string UserAlreadyExist {
        get {
            return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Пользователь с этой ролью уже существует.
    /// </summary>
    public static string UserAlreadyExistThisRole {
        get {
            return ResourceManager.GetString("UserAlreadyExistThisRole", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Пользователь не найден.
    /// </summary>
    public static string UserNotFound {
        get {
            return ResourceManager.GetString("UserNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Роли пользователей.
    /// </summary>
    public static string UserRolesNotFound {
        get {
            return ResourceManager.GetString("UserRolesNotFound", resourceCulture);
        }
    }
}
